### ISSUE TITLE
Duplicate workspace name

### ISSUE THREAD

**Issue by sbue** [pax-k/pax-react-native-starter#1]
```
/pax-react-native-starter/apps/storybook conflicts with /pax-react-native-starter/apps/next
```

**Comment by sbue** [comment]
Once renamed from "next" to "storybook", getting the following build error: `TypeError: Cannot read properties of undefined (reading 'animations')`

**Comment by pax-k** [comment]
Hey @sbue ! Thanks for bringing this up. I just pushed a fix. My bad, the contents of `apps/storybook` were an exact copy of `apps/next` and had nothing to do with Storybook. Issue comes since I reconstructed this repo from my original sources and I wrongfully handled/copied some of the files, then pushed without proper testing. Everything else should work as expected.

Please try again:
```
git pull
yarn
yarn start:sb
```

Feel free to test and ping me if you need further help.
